# Generated by Django 4.2 on 2025-12-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_user'),
        ('educations', '0002_educations_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educations',
            new_name='Education',
        ),
    ]
