# Generated by Django 4.2 on 2025-12-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_workexperience_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
